### ISSUE TITLE
Error messages when compiling

### ISSUE THREAD

**Issue by W3JDR** [rheslip/Teensy_SDR#3]
Trying to compile in Arduino 1.8.1. Getting these error messages:

In file included from C:\Users\Joe Rocci\Documents\Arduino\Teensy_SDR-master\Teensy_SDR\Teensy_SDR.ino:46:0:

Teensy_SDR: In function 'void loop()':
C:\Users\Joe Rocci\Documents\Arduino\libraries\Teensy_SDR/display.h:4:17: error: 'ILI9341_RED' was not declared in this scope

 #define RED     ILI9341_RED

                 ^

C:\Users\Joe Rocci\Documents\Arduino\Teensy_SDR-master\Teensy_SDR\Teensy_SDR.ino:475:23: note: in expansion of macro 'RED'

      tft.setTextColor(RED); 

                       ^

C:\Users\Joe Rocci\Documents\Arduino\libraries\Teensy_SDR/display.h:2:17: error: 'ILI9341_BLACK' was not declared in this scope

 #define BLACK   ILI9341_BLACK

                 ^

C:\Users\Joe Rocci\Documents\Arduino\Teensy_SDR-master\Teensy_SDR\Teensy_SDR.ino:495:35: note: in expansion of macro 'BLACK'

      tft.fillRect(75, 72, 11, 10, BLACK);// erase text

                                   ^

Teensy_SDR: In function 'void setup_RX(int)':
Teensy_SDR:569: error: 'RX_hilbertm45' was not declared in this scope
   Hilbert45_I.begin(RX_hilbertm45,HILBERT_COEFFS);

                     ^

Teensy_SDR:570: error: 'RX_hilbert45' was not declared in this scope
   Hilbert45_Q.begin(RX_hilbert45,HILBERT_COEFFS);

                     ^

Teensy_SDR:573: error: 'firbpf_lsb' was not declared in this scope
     FIR_BPF.begin(firbpf_lsb,BPF_COEFFS);       // 2.4kHz LSB filter

                   ^

Teensy_SDR:574: error: 'firbpf_usb' was not declared in this scope
   else FIR_BPF.begin(firbpf_usb,BPF_COEFFS);       // 2.4kHz USB filter

                      ^

Teensy_SDR:578: error: 'postfir_700' was not declared in this scope
       postFIR.begin(postfir_700,COEFF_700);     // 700 Hz LSB filter

                     ^

Teensy_SDR:578: error: 'COEFF_700' was not declared in this scope
       postFIR.begin(postfir_700,COEFF_700);     // 700 Hz LSB filter

                                 ^

Teensy_SDR:579: error: 'LSB_NARROW' was not declared in this scope
       show_bandwidth(LSB_NARROW);

                      ^

Teensy_SDR:583: error: 'postfir_lpf' was not declared in this scope
       postFIR.begin(postfir_lpf,COEFF_LPF);     // 2.4kHz LSB filter

                     ^

Teensy_SDR:583: error: 'COEFF_LPF' was not declared in this scope
       postFIR.begin(postfir_lpf,COEFF_LPF);     // 2.4kHz LSB filter

                                 ^

Teensy_SDR:584: error: 'LSB_WIDE' was not declared in this scope
       show_bandwidth(LSB_WIDE);

                      ^

Teensy_SDR:589: error: 'USB_NARROW' was not declared in this scope
       show_bandwidth(USB_NARROW);

                      ^

Teensy_SDR:594: error: 'USB_WIDE' was not declared in this scope
       show_bandwidth(USB_WIDE);

                      ^

Teensy_SDR: In function 'void setup_TX(int)':
Teensy_SDR:626: error: 'TX_hilbert45' was not declared in this scope
       Hilbert45_I.begin(TX_hilbert45,HILBERT_COEFFS);

                         ^

Teensy_SDR:627: error: 'TX_hilbertm45' was not declared in this scope
       Hilbert45_Q.begin(TX_hilbertm45,HILBERT_COEFFS);

                         ^

Multiple libraries were found for "SD.h"
 Used: C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\SD
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
Multiple libraries were found for "Adafruit_GFX.h"
 Used: C:\Program Files (x86)\Arduino\hardware\teensy\avr\libraries\Adafruit_GFX
 Not used: C:\Users\Joe Rocci\Documents\Arduino\libraries\Adafruit_GFX_Library
'RX_hilbertm45' was not declared in this scope

Can someone offer some guidance?
